// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens(user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, is_revoked, expires_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IsRevoked bool               `json:"is_revoked"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
	)
	return i, err
}

const findActiveRefreshToken = `-- name: FindActiveRefreshToken :one
SELECT (id, user_id, token_hash, is_revoked, expires_at) FROM refresh_tokens WHERE is_revoked = false AND user_id = $1 LIMIT 1
`

func (q *Queries) FindActiveRefreshToken(ctx context.Context, userID int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, findActiveRefreshToken, userID)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET is_revoked = true WHERE is_revoked = false AND user_id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, userID)
	return err
}
